### ISSUE TITLE
Thread 1: Fatal error: Range requires lowerBound <= upperBound

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/Version-Control-Kit#24]
### Description

<img width="971" alt="Screenshot 2024-03-03 alle 18 18 00" src="https://github.com/AuroraEditor/Version-Control-Kit/assets/20476002/f9f3f27b-0611-4269-8020-ba42c8cacfef">

### To Reproduce

1) Create a single file project
2) Git init
3) Open the project with AE

### Version information

Aurora Editor: 1.0 (1)
Commit: 2afdf0378f8425a1722d66bf4dbcfdfc99f1f10b
MacOS: 14.1.1 (23B81)
Xcode: 15.2 (15C500b)

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
